### ISSUE TITLE
It is impossible to get a release due to a request for agreement with the license.

### ISSUE THREAD

**Issue by YuriSilenok** [kivy/buildozer#1403]
### Versions

* Python: 3.6
* OS: Ubuntu 16.04.7 LTS
* Buildozer: buildozer-1.2.0

### Description

I want to set up continuous integration on Travis.
To do this, I wrote the configuration.
```yml
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - git clone https://github.com/kivy/buildozer.git
  - cd buildozer
  - python3 setup.py install
  - cd ..
  - buildozer init
  - buildozer android release
```
Since I cannot enter any values through the terminal, I cannot agree with the license offered to me. 
The log can be viewed [here](https://api.travis-ci.com/v3/job/557961901/log.txt).
### buildozer.spec
Command:
```sh
buildozer android release
```

Spec file:
```
Unfortunately, I do not yet know how to get this file from a remote server.
```

### Logs

```
Accept? (y/N): 
```
