### ISSUE TITLE
Error "Aidl not found, please install it."

### ISSUE THREAD

**Issue by ckaldemeyer** [kivy/buildozer#1416]
### Versions

* Python: 3.9
* OS: Debian Linux (Bullseye)
* Buildozer: 1.3.0

### Description

When I run buildozer errors of missing packages occur.

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
##############################################################################
# about buildozer.spec : https://buildozer.readthedocs.io/en/latest/specifications.html
##############################################################################

[app]

# (str) Title of your application
title = induperator

# (str) Package name
package.name = induperator

# (str) Package domain (needed for android/ios packaging)
package.domain = org.induperator.edu

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,ogg

# (list) List of inclusions using pattern matching
source.include_patterns = data/*.png, sound/*.ogg

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3crystax==3.6,kivy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
icon.filename = %(source.dir)s/data/icon512x512.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.10.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET,CHANGE_WIFI_MULTICAST_STATE,ACCESS_NETWORK_STATE,ACCESS_WIFI_STATE

# (int) Android API to use
# see https://developer.android.com/distribute/best-practices/develop/target-sdk
android.api = 27

# (int) Minimum API required
#android.minapi = 19

# (int) Android SDK version to use
android.sdk = 23

# (str) Android NDK version to use
#android.ndk = 10.3.2

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
android.ndk_path = ~/Desktop/crystax-ndk-10.3.2

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path = ~/Desktop/platform-tools

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) python-for-android branch to use, defaults to stable
#p4a.branch = stable

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

### Logs

Error

```
...
---------------------------------------
Accept? (y/N): Skipping following packages as the license is not accepted:
Android SDK Build-Tools 33-rc2
The following packages can not be installed since their licenses or those of the packages they depend on were not accepted:
  build-tools;33.0.0-rc2
[=======================================] 100% Computing updates...             
# Check that aidl can be executed
# build-tools folder not found /root/.buildozer/android/platform/android-sdk/build-tools
# Search for Aidl
# Aidl not found, please install it.
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```

**Comment by ckaldemeyer** [comment]
I am using this in a gitlab pipeline:

```
image: python:3.9

before_script:
  - apt-get update
  # install buildozer dependencies
  - apt-get -y install git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
  # install openjdk-13-jdk manually
  # https://computingforgeeks.com/install-oracle-java-13-on-ubuntu-debian/
  - apt-get -y install -y curl
  - curl -O https://download.java.net/java/GA/jdk13/5b8a42f3905b406298b72d750b6919f6/33/GPL/openjdk-13_linux-x64_bin.tar.gz
  - tar xvf openjdk-13_linux-x64_bin.tar.gz
  - mv jdk-13 /opt/
  - tee /etc/profile.d/jdk13.sh <<EOF
  - export JAVA_HOME=/opt/jdk-13
  - export PATH=\$PATH:\$JAVA_HOME/bin
  - EOF
  - source /etc/profile.d/jdk13.sh
  - echo $JAVA_HOME
  - java -version
  # fix error "Aidl not found, please install it." in build process
  #- apt-get -y install build-essential
  #- apt-get -y install libstdc++6
  # https://stackoverflow.com/questions/55902147/buildozer-not-finding-aidl
  # https://stackoverflow.com/questions/45901878/why-does-buildozer-show-aidl-not-found-please-install-it-even-after-i-inst
  - apt-get -y install android-sdk
  #- apt-get -y install aidl
  # install python packages
  - pip install --user --upgrade buildozer
  - export "PATH=$PATH:~/.local/bin/" >> ~/.bashrc # add buildozer to PATH
  - pip install --user --upgrade Cython==0.29.19 virtualenv
  - export "PATH=$PATH:/root/.local/bin" >> ~/.bashrc # add cython to PATH
  - pip install --user kivy kivymd

run-buildozer:
  script:
    # create a new user to run all buildozer commands because
    # it does not like to be run as root user
    - adduser --disabled-password my_user
    - chown -R my_user:my_user /root # add rights to access /root/.buildozer
    #- su -m my_user -c "buildozer init" # run only once initially
    - su -m my_user -c "buildozer android debug"
    - su -m my_user -c "buildozer android clean"
  only:
    - main

```

What am I missing?
