### ISSUE TITLE
subprocess.CalledProcessError: Command 'buildozer android debug' returned non-zero exit status 1.`

### ISSUE THREAD

**Issue by Siam-Rayhan1** [kivy/buildozer#1622]
3 months ago i have built an apk via Github Action.But now in the same way I'm trying to build another apk but getting error.Everything looks pretty fine as before but not working.This is my build.yml 

```
name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:

          command: buildozer android debug
          buildozer_version: master 

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
``` 

I'm getting this error.

```
export BUILDLIB_PATH='/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/build/lib.linux-x86_64-3.10'
export PYTHONNOUSERSITE='1'
export LANG='en_GB.UTF-8'
export PYTHONPATH='/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib:/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib/site-packages:/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/build/lib.linux-x86_64-3.10:/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/build/scripts-3.10:/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/build/temp.linux-x86_64-3.10'
export LIBLINK='NOTNONE'
export COPYLIBS='1'
export LIBLINK_PATH='/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/objects_pyjnius'
export NDKPLATFORM='NOTNONE'

[INFO]:    COMMAND:
cd /github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/pyjnius && /github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v

[WARNING]: ERROR: /github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 failed!
# Command failed: ['/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=sampleapk', '--bootstrap=sdl2', '--requirements=python3,kivy==2.0.0,kivymd==0.104.2,pillow==8.3.1,certifi', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/github/workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     GITHUB_STATE = '/github/file_commands/save_state_62b73df0-92ac-43b0-bb49-f39f75bebc7e'
#     ACTIONS_RUNTIME_TOKEN = '***'
#     ACTIONS_CACHE_URL = 'https://artifactcache.actions.githubusercontent.com/3sZTv9hQF7XNYXwZ4NmHwAaH7sJU7D21hP82nD5g0zMfFX3Q7d/'
#     USER = 'user'
#     LANGUAGE = 'en_US.UTF-8'
#     CI = 'true'
#     HOSTNAME = '576accd612e7'
#     GITHUB_ENV = '/github/file_commands/set_env_62b73df0-92ac-43b0-bb49-f39f75bebc7e'
#     RUNNER_ENVIRONMENT = 'github-hosted'
#     WORK_DIR = '/home/user/hostcwd'
#     HOME = '/home/user'
#     SRC_DIR = '/home/user/src'
#     RUNNER_TEMP = '/home/runner/work/_temp'
#     GITHUB_EVENT_PATH = '/github/workflow/event.json'
#     GITHUB_REPOSITORY_OWNER = 'Siam-Rayhan1'
#     PYTHONUNBUFFERED = '1'
#     GITHUB_RETENTION_DAYS = '90'
#     GITHUB_HEAD_REF = ''
#     GITHUB_REPOSITORY_OWNER_ID = '138190908'
#     GITHUB_GRAPHQL_URL = 'https://api.github.com/graphql'
#     HOME_DIR = '/home/user'
#     BUILDOZER_WARN_ON_ROOT = '0'
#     RUNNER_OS = 'Linux'
#     GITHUB_API_URL = 'https://api.github.com'
#     ACTIONS_RUNTIME_URL = 'https://pipelines.actions.githubusercontent.com/3sZTv9hQF7XNYXwZ4NmHwAaH7sJU7D21hP82nD5g0zMfFX3Q7d/'
#     GITHUB_WORKFLOW = 'CI'
#     APP_ANDROID_ACCEPT_SDK_LICENSE = '1'
#     GITHUB_RUN_ID = '5429489762'
#     GITHUB_WORKFLOW_SHA = 'f94a6c054cf4e189c4fa93a784ed674e40081cdc'
#     GITHUB_BASE_REF = ''
#     GITHUB_REF_TYPE = 'branch'
#     GITHUB_ACTION_REPOSITORY = 'ArtemSBulgakov/buildozer-action'
#     GITHUB_WORKFLOW_REF = 'Siam-Rayhan1/Test/.github/workflows/build.yml@refs/heads/master'
#     PATH = '/github/workspace/./.buildozer_global/android/platform/apache-ant-1.9.4/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#     RUNNER_TOOL_CACHE = '/opt/hostedtoolcache'
#     GITHUB_TRIGGERING_ACTOR = 'Siam-Rayhan1'
#     RUNNER_ARCH = 'X64'
#     GITHUB_RUN_NUMBER = '12'
#     GITHUB_ACTION = 'buildozer'
#     LANG = 'en_US.UTF-8'
#     INPUT_WORKDIR = '.'
#     GITHUB_REPOSITORY = 'Siam-Rayhan1/Test'
#     GITHUB_REF_NAME = 'master'
#     RUNNER_NAME = 'GitHub Actions 1'
#     GITHUB_ACTION_REF = 'v1'
#     GITHUB_ACTIONS = 'true'
#     GITHUB_REPOSITORY_ID = '660482529'
#     GITHUB_REF_PROTECTED = 'false'
#     BUILDOZER_BIN = './bin'
#     INPUT_COMMAND = 'buildozer android debug'
#     GITHUB_JOB = 'build'
#     GITHUB_WORKSPACE = '/github/workspace'
#     BUILDOZER_BUILD_DIR = './.buildozer'
#     GITHUB_RUN_ATTEMPT = '1'
#     GITHUB_SHA = 'f94a6c054cf4e189c4fa93a784ed674e40081cdc'
#     GITHUB_ACTOR = 'Siam-Rayhan1'
#     GITHUB_REF = 'refs/heads/master'
#     INPUT_BUILDOZER_VERSION = 'master'
#     GITHUB_PATH = '/github/file_commands/add_path_62b73df0-92ac-43b0-bb49-f39f75bebc7e'
#     RUNNER_WORKSPACE = '/home/runner/work/Test'
#     GITHUB_ACTOR_ID = '138190908'
#     LC_ALL = 'en_US.UTF-8'
#     PWD = '/github/workspace'
#     GITHUB_SERVER_URL = 'https://github.com'
#     GITHUB_EVENT_NAME = 'push'
#     GITHUB_OUTPUT = '/github/file_commands/set_output_62b73df0-92ac-43b0-bb49-f39f75bebc7e'
#     INPUT_REPOSITORY_ROOT = '.'
#     GITHUB_STEP_SUMMARY = '/github/file_commands/step_summary_62b73df0-92ac-43b0-bb49-f39f75bebc7e'
#     PACKAGES_PATH = '/github/workspace/./.buildozer_global/android/packages'
#     ANDROIDSDK = '/github/workspace/./.buildozer_global/android/platform/android-sdk'
#     ANDROIDNDK = '/github/workspace/./.buildozer_global/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
Traceback (most recent call last):
  File "/action/entrypoint.py", line 159, in <module>
    main()
  File "/action/entrypoint.py", line 27, in main
    run_command(env["INPUT_COMMAND"])
  File "/action/entrypoint.py", line 135, in run_command
    retcode = subprocess.check_call(command, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'buildozer android debug' returned non-zero exit status 1.
``` 

Please help me.
