### ISSUE TITLE
 error: C compiler cannot create executables

### ISSUE THREAD

**Issue by tamano123** [kivy/buildozer#897]
### Versions

* Python: 2.7.12
* OS: Ubuntu 16.04.5 LTS
* Buildozer: 0.40.dev0

### Description
Hello,

- I downloaded the Zen-Code's Virtual machine 
- I tried to create the .apk for the Touchtracer example targeting python3

Thank you for your help !
### buildozer.spec
Command:
```sh
buildozer android debug logcat
```

Spec file:
```
[app]

# (str) Title of your application
title = TouchTracer

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = python3,kivy==1.10.1

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Android API to use
android.api = 27

# (int) Minimum API required
android.minapi = 21

# (int) Android SDK version to use
android.sdk = 28

# (str) Android NDK version to use
#android.ndk = r16b

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
android.ndk_path = /home/kivy/Android/android-ndk-r16b/

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
android.sdk_path = /home/kivy/Android/android-sdk-28/

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) python-for-android branch to use, defaults to stable
#p4a.branch = stable

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir = /home/kivy/Repos/python-for-android/

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

### Logs

```
 STDOUT:
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking for python3.7... no
checking for python3... python3
checking for python interpreter for cross build... python
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... checking for --without-gcc... no
checking for --with-icc... no
checking for arm-linux-androideabi-gcc... /home/kivy/Android/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-none-linux-androideabi -gcc-toolchain /home/kivy/Android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
checking whether the C compiler works... no
configure: error: in `/home/kivy/Repos/Python3/kivy/examples/demo/touchtracer/.buildozer/android/platform/build/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/android-build':
configure: error: C compiler cannot create executables
See `config.log' for more details


  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy==1.10.1 --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/kivy/Repos/Python3/kivy/examples/demo/touchtracer/.buildozer/android/platform/build" --ndk-api=21
# ENVIRONMENT:
#     XAUTHORITY = '/home/kivy/.Xauthority'
#     WINDOWID = '67109917'
#     GLADE_PIXMAP_PATH = ':'
#     XDG_GREETER_DATA_DIR = '/var/lib/lightdm-data/kivy'
#     QT4_IM_MODULE = ''
#     ANDROIDMINAPI = '21'
#     UPSTART_EVENTS = 'started xsession'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     XDG_SESSION_TYPE = 'x11'
#     QT_IM_MODULE = ''
#     LOGNAME = 'kivy'
#     USER = 'kivy'
#     PATH = '/home/kivy/.buildozer/android/platform/apache-ant-1.9.4/bin:/bin:/home/kivy/bin:/home/kivy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
#     XDG_VTNR = '7'
#     GNOME_KEYRING_CONTROL = ''
#     PACKAGES_PATH = '/home/kivy/.buildozer/android/packages'
#     DISPLAY = ':0.0'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     LANG = 'en_ZA.UTF-8'
#     TERM = 'xterm'
#     SHELL = '/bin/bash'
#     XDG_SESSION_PATH = '/org/freedesktop/DisplayManager/Session0'
#     QT_STYLE_OVERRIDE = 'gtk'
#     LANGUAGE = 'en_ZA:en'
#     SESSION_MANAGER = 'local/kivy-complete:@/tmp/.ICE-unix/1236,unix/kivy-complete:/tmp/.ICE-unix/1236'
#     SHLVL = '1'
#     QT_LINUX_ACCESSIBILITY_ALWAYS_ON = '1'
#     MANDATORY_PATH = '/usr/share/gconf/xubuntu.mandatory.path'
#     CLUTTER_IM_MODULE = ''
#     JAVA_HOME = '/usr/lib/jvm/java-8-openjdk-amd64'
#     QT_ACCESSIBILITY = '1'
#     SESSION = 'xubuntu'
#     GTK_OVERLAY_SCROLLING = '0'
#     UPSTART_INSTANCE = ''
#     SESSIONTYPE = ''
#     XMODIFIERS = ''
#     GLADE_CATALOG_PATH = ':'
#     GPG_AGENT_INFO = '/home/kivy/.gnupg/S.gpg-agent:0:1'
#     HOME = '/home/kivy'
#     CLUTTER_BACKEND = 'x11'
#     ANDROIDSDK = '/home/kivy/Android/android-sdk-28'
#     XDG_SESSION_DESKTOP = 'xubuntu'
#     GLADE_MODULE_PATH = ':'
#     INSTANCE = ''
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     GDMSESSION = 'xubuntu'
#     IM_CONFIG_PHASE = '1'
#     UPSTART_JOB = 'startxfce4'
#     XDG_SEAT_PATH = '/org/freedesktop/DisplayManager/Seat0'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_CURRENT_DESKTOP = 'XFCE'
#     XDG_SESSION_ID = 'c1'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:abstract=/tmp/dbus-ppr4kIGktD'
#     _ = '/usr/local/bin/buildozer'
#     GNOME_KEYRING_PID = ''
#     GTK_IM_MODULE = ''
#     DESKTOP_SESSION = 'xubuntu'
#     UPSTART_SESSION = 'unix:abstract=/com/ubuntu/upstart-session/1000/999'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-xubuntu:/usr/share/upstart/xdg:/etc/xdg:/etc/xdg'
#     DEFAULTS_PATH = '/usr/share/gconf/xubuntu.default.path'
#     OLDPWD = '/home/kivy/Repos/Python3/kivy/examples/demo/touchtracer/buildozer'
#     ANDROIDNDK = '/home/kivy/Android/android-ndk-r16b'
#     GDM_LANG = 'en_US'
#     XDG_DATA_DIRS = '/usr/share/xubuntu:/usr/share/xfce4:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop:/usr/share'
#     PWD = '/home/kivy/Repos/Python3/kivy/examples/demo/touchtracer'
#     JOB = 'dbus'
#     ANDROIDAPI = '27'
#     COLORTERM = 'xfce4-terminal'
#     XDG_MENU_PREFIX = 'xfce-'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_SEAT = 'seat0'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error

# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```
[config.log](https://github.com/kivy/buildozer/files/3186383/config.log)
